
version: '3.2'

services:

  freeradius:
    container_name: freeradius
    image: ghcr.io/nextpertise/freeradius-amqp/freeradius-amqp:main
    command: sh -c 'sleep 10; freeradius -X'
    restart: always
    environment:
        - TZ=UTC
    ports:
        - "1812:1812"
        - "1813:1812"
    volumes:
        - ./data/freeradius/:/etc/freeradius/
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
    - default
    image: rabbitmq:3.8-management
    restart: always
    environment:
      - TZ=UTC
      - RABBITMQ_DEFAULT_USER=radiustest
      - RABBITMQ_DEFAULT_PASS=radiustest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq/"
    ports:     
      - 5672:5672 
      - 15672:15672
  app:
    container_name: app
    image: pythonamqp:latest
    depends_on:
      - rabbitmq
    command: tail -f /dev/null 
    restart: on-failure
    volumes:
      - ./data/python:/app
    environment:
      - TZ=UTC

