name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: VaultVulp/gp-docker-action@1.1.12
      with:
        github-token: abc
        image-name: ghcr.io/nextpertise/freeradius-amqp
      working-directory: ./build
